// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpENx8drVc4_QZedbXYvgWMK8hz7UKFgE',
    appId: '1:392662072726:web:8e049d44d78cd91f4531b7',
    messagingSenderId: '392662072726',
    projectId: 'snote-e8384',
    authDomain: 'snote-e8384.firebaseapp.com',
    storageBucket: 'snote-e8384.firebasestorage.app',
    measurementId: 'G-NZ1NFG7XHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxprTuQ6Q28-ejIhGGVVeFmNUxDIeMtM',
    appId: '1:392662072726:android:061658baf9d447e44531b7',
    messagingSenderId: '392662072726',
    projectId: 'snote-e8384',
    storageBucket: 'snote-e8384.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpENx8drVc4_QZedbXYvgWMK8hz7UKFgE',
    appId: '1:392662072726:web:71a5c889bb8eada84531b7',
    messagingSenderId: '392662072726',
    projectId: 'snote-e8384',
    authDomain: 'snote-e8384.firebaseapp.com',
    storageBucket: 'snote-e8384.firebasestorage.app',
    measurementId: 'G-TBKBCQQJKT',
  );
}


